using System.Diagnostics.CodeAnalysis;
using ParkingApp.Domain.Enums;
using ParkingApp.BuildingBlocks.Domain;

namespace ParkingApp.Corporate.Domain;

/// <summary>
/// Company billing invoice for a closed period. Snapshot of charges; settlement is offline (mark paid).
/// </summary>
public class CorporateInvoice : BaseEntity
{
    public const int MaxPeriodDays = 92;
    public const int MaxLineItems = 500;
    public const string DefaultCurrency = "INR";

    public Guid CompanyId { get; private set; }
    public string InvoiceNumber { get; private set; } = string.Empty;
    public BillingType BillingTypeSnapshot { get; private set; }
    public DateOnly PeriodStart { get; private set; }
    public DateOnly PeriodEnd { get; private set; }
    public CorporateInvoiceStatus Status { get; private set; } = CorporateInvoiceStatus.Draft;
    public string Currency { get; private set; } = DefaultCurrency;
    public decimal Subtotal { get; private set; }
    public decimal TaxAmount { get; private set; }
    public decimal TotalAmount { get; private set; }
    public Guid GeneratedByUserId { get; private set; }

    public DateTime? IssuedAt { get; private set; }
    public Guid? IssuedByUserId { get; private set; }
    public DateTime? PaidAt { get; private set; }
    public Guid? PaidByUserId { get; private set; }
    public string? PaymentReference { get; private set; }
    public string? PaymentNotes { get; private set; }
    public DateTime? VoidedAt { get; private set; }
    public Guid? VoidedByUserId { get; private set; }
    public string? VoidReason { get; private set; }

    public virtual Company Company { get; private set; } = null!;
    public virtual ICollection<CorporateInvoiceLineItem> LineItems { get; private set; } = new List<CorporateInvoiceLineItem>();

    // Required for EF Core materialization — no business logic.
    [ExcludeFromCodeCoverage]
    private CorporateInvoice()
    {
    }

    /// <summary>
    /// Creates a draft invoice with pre-computed line drafts.
    /// </summary>
    public static CorporateInvoice Create(
        Guid companyId,
        BillingType billingType,
        DateOnly periodStart,
        DateOnly periodEnd,
        Guid generatedByUserId,
        IReadOnlyList<CorporateInvoiceLineDraft> lines,
        string currency = DefaultCurrency,
        decimal taxAmount = 0m)
    {
        if (companyId == Guid.Empty)
        {
            throw new ArgumentException("Company ID is required.", nameof(companyId));
        }

        if (generatedByUserId == Guid.Empty)
        {
            throw new ArgumentException("Generated by user ID is required.", nameof(generatedByUserId));
        }

        ValidatePeriod(periodStart, periodEnd);

        if (lines is null)
        {
            throw new ArgumentNullException(nameof(lines));
        }

        if (lines.Count > MaxLineItems)
        {
            throw new InvalidOperationException(
                $"Invoice cannot exceed {MaxLineItems} line items. Narrow the billing period and try again.");
        }

        if (taxAmount < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(taxAmount), "Tax amount cannot be negative.");
        }

        if (string.IsNullOrWhiteSpace(currency))
        {
            currency = DefaultCurrency;
        }

        var invoice = new CorporateInvoice
        {
            CompanyId = companyId,
            InvoiceNumber = GenerateInvoiceNumber(),
            BillingTypeSnapshot = billingType,
            PeriodStart = periodStart,
            PeriodEnd = periodEnd,
            Status = CorporateInvoiceStatus.Draft,
            Currency = currency.Trim().ToUpperInvariant(),
            TaxAmount = Math.Round(taxAmount, 2, MidpointRounding.AwayFromZero),
            GeneratedByUserId = generatedByUserId
        };

        foreach (var draft in lines)
        {
            var line = CorporateInvoiceLineItem.Create(
                invoice.Id,
                draft.LineType,
                draft.Description,
                draft.Quantity,
                draft.UnitAmount,
                draft.AllocationId,
                draft.BookingId);
            invoice.LineItems.Add(line);
        }

        invoice.RecalculateTotals();
        return invoice;
    }

    public void Issue(Guid adminUserId)
    {
        EnsureActor(adminUserId);

        if (Status != CorporateInvoiceStatus.Draft)
        {
            throw new InvalidOperationException("Only draft invoices can be issued.");
        }

        Status = CorporateInvoiceStatus.Issued;
        IssuedAt = DateTime.UtcNow;
        IssuedByUserId = adminUserId;
        UpdatedAt = DateTime.UtcNow;
    }

    public void MarkPaid(Guid adminUserId, string? paymentReference = null, string? paymentNotes = null)
    {
        EnsureActor(adminUserId);

        if (Status != CorporateInvoiceStatus.Issued)
        {
            throw new InvalidOperationException("Only issued invoices can be marked paid.");
        }

        Status = CorporateInvoiceStatus.Paid;
        PaidAt = DateTime.UtcNow;
        PaidByUserId = adminUserId;
        PaymentReference = string.IsNullOrWhiteSpace(paymentReference) ? null : paymentReference.Trim();
        PaymentNotes = string.IsNullOrWhiteSpace(paymentNotes) ? null : paymentNotes.Trim();
        UpdatedAt = DateTime.UtcNow;
    }

    public void Void(Guid adminUserId, string reason)
    {
        EnsureActor(adminUserId);

        if (Status is CorporateInvoiceStatus.Paid or CorporateInvoiceStatus.Void)
        {
            throw new InvalidOperationException("Paid or already void invoices cannot be voided.");
        }

        if (string.IsNullOrWhiteSpace(reason) || reason.Trim().Length < 3)
        {
            throw new ArgumentException("Void reason must be at least 3 characters.", nameof(reason));
        }

        Status = CorporateInvoiceStatus.Void;
        VoidedAt = DateTime.UtcNow;
        VoidedByUserId = adminUserId;
        VoidReason = reason.Trim();
        UpdatedAt = DateTime.UtcNow;
    }

    public static void ValidatePeriod(DateOnly periodStart, DateOnly periodEnd)
    {
        if (periodEnd < periodStart)
        {
            throw new ArgumentException("Period end must be on or after period start.");
        }

        var days = periodEnd.DayNumber - periodStart.DayNumber + 1;
        if (days > MaxPeriodDays)
        {
            throw new ArgumentException($"Billing period cannot exceed {MaxPeriodDays} days.");
        }
    }

    private void RecalculateTotals()
    {
        Subtotal = Math.Round(LineItems.Sum(l => l.Amount), 2, MidpointRounding.AwayFromZero);
        TotalAmount = Math.Round(Subtotal + TaxAmount, 2, MidpointRounding.AwayFromZero);
    }

    private static string GenerateInvoiceNumber() =>
        $"CINV-{DateTime.UtcNow:yyyyMMdd}-{Guid.NewGuid().ToString("N")[..6].ToUpperInvariant()}";

    private static void EnsureActor(Guid userId)
    {
        if (userId == Guid.Empty)
        {
            throw new ArgumentException("User ID is required.", nameof(userId));
        }
    }
}

/// <summary>
/// Intermediate line used when building an invoice before persistence.
/// </summary>
public sealed record CorporateInvoiceLineDraft(
    CorporateInvoiceLineType LineType,
    string Description,
    decimal Quantity,
    decimal UnitAmount,
    Guid? AllocationId = null,
    Guid? BookingId = null);
