using System.ComponentModel.DataAnnotations;
using ParkingApp.Marketplace.Contracts.Enums;
using ParkingApp.BuildingBlocks.Enums;

namespace ParkingApp.Marketplace.Contracts.DTOs;

public record ReservationPeriodDto(
    DateTime StartDateTime,
    DateTime EndDateTime,
    int? SlotNumber = null,
    string? UserName = null
);

public record ParkingSpaceDto(
    Guid Id,
    Guid OwnerId,
    string OwnerName,
    string Title,
    string Description,
    string Address,
    string City,
    string State,
    string Country,
    string PostalCode,
    double Latitude,
    double Longitude,
    ParkingType ParkingType,
    int TotalSpots,
    int AvailableSpots,
    decimal HourlyRate,
    decimal DailyRate,
    decimal WeeklyRate,
    decimal MonthlyRate,
    TimeSpan OpenTime,
    TimeSpan CloseTime,
    bool Is24Hours,
    List<string> Amenities,
    List<VehicleType> AllowedVehicleTypes,
    List<string> ImageUrls,
    bool IsActive,
    bool IsVerified,
    double AverageRating,
    int TotalReviews,
    string? SpecialInstructions,
    DateTime CreatedAt,
    double? DistanceKm = null,
    int? EstimatedTimeMinutes = null,
    List<ReservationPeriodDto>? ActiveReservations = null,
    string? ZoneCode = null,
    Guid? CompanyOwnerId = null,
    ParkingSpaceOwnershipType OwnershipType = ParkingSpaceOwnershipType.IndividualVendor,
    bool IsCorporateOnly = false,
    bool IsLprEnabled = false,
    bool IsDynamicPricingEnabled = false,
    decimal DynamicMinMultiplier = 0.80m,
    decimal DynamicMaxMultiplier = 1.75m,
    decimal PeakHourMultiplier = 1.25m,
    decimal WeekendMultiplier = 1.15m,
    bool HasEvCharging = false,
    int EvChargerCount = 0,
    decimal EvChargingRatePerHour = 0m,
    decimal EvIdleRatePerHour = 0m,
    int EvIdleGraceMinutes = 15,
    EvPricingMode EvPricingMode = EvPricingMode.Hourly,
    decimal EvRatePerKwh = 0m,
    ListingCategory ListingCategory = ListingCategory.Commercial,
    bool InstantBook = false,
    string TimeZoneId = "UTC",
    /// <summary>Effective hourly rate after dynamic pricing (search “from ₹…”).</summary>
    decimal EffectiveHourlyRate = 0m,
    bool DynamicPricingApplied = false,
    decimal? DynamicMultiplier = null,
    bool IsBayGuidanceEnabled = false,
    bool IsValetEnabled = false,
    string? DefaultFacilityLevel = null,
    string? DefaultFacilityZone = null,
    string? IndoorGuidanceNotes = null
);

public record CreateParkingSpaceDto(
    [Required] string Title,
    [Required] string Description,
    [Required] string Address,
    [Required] string City,
    [Required] string State,
    [Required] string Country,
    [Required] string PostalCode,
    double Latitude,
    double Longitude,
    ParkingType ParkingType,
    [Range(1, 1000)] int TotalSpots,
    [Range(0, 10000)] decimal HourlyRate,
    [Range(0, 100000)] decimal DailyRate,
    [Range(0, 500000)] decimal WeeklyRate,
    [Range(0, 2000000)] decimal MonthlyRate,
    TimeSpan? OpenTime,
    TimeSpan? CloseTime,
    bool Is24Hours = true,
    List<string>? Amenities = null,
    List<VehicleType>? AllowedVehicleTypes = null,
    List<string>? ImageUrls = null,
    string? SpecialInstructions = null,
    string? ZoneCode = null,
    bool IsLprEnabled = false,
    bool IsDynamicPricingEnabled = false,
    decimal? DynamicMinMultiplier = null,
    decimal? DynamicMaxMultiplier = null,
    decimal? PeakHourMultiplier = null,
    decimal? WeekendMultiplier = null,
    bool HasEvCharging = false,
    int? EvChargerCount = null,
    decimal? EvChargingRatePerHour = null,
    decimal? EvIdleRatePerHour = null,
    int? EvIdleGraceMinutes = null,
    EvPricingMode EvPricingMode = EvPricingMode.Hourly,
    decimal? EvRatePerKwh = null,
    ListingCategory ListingCategory = ListingCategory.Commercial,
    bool? InstantBook = null,
    string? TimeZoneId = null,
    bool IsBayGuidanceEnabled = false,
    bool IsValetEnabled = false,
    string? DefaultFacilityLevel = null,
    string? DefaultFacilityZone = null,
    string? IndoorGuidanceNotes = null,
    /// <summary>Physical 2-wheeler bay capacity. Omit with 4W for untyped total-only capacity.</summary>
    [Range(0, 1000)] int? TwoWheelerPhysicalSpots = null,
    /// <summary>Physical 4-wheeler bay capacity. Omit with 2W for untyped total-only capacity.</summary>
    [Range(0, 1000)] int? FourWheelerPhysicalSpots = null
);

public record UpdateParkingSpaceDto(
    string? Title,
    string? Description,
    string? Address,
    string? City,
    string? State,
    string? Country,
    string? PostalCode,
    double? Latitude,
    double? Longitude,
    ParkingType? ParkingType,
    int? TotalSpots,
    decimal? HourlyRate,
    decimal? DailyRate,
    decimal? WeeklyRate,
    decimal? MonthlyRate,
    TimeSpan? OpenTime,
    TimeSpan? CloseTime,
    bool? Is24Hours,
    List<string>? Amenities,
    List<VehicleType>? AllowedVehicleTypes,
    List<string>? ImageUrls,
    string? SpecialInstructions,
    bool? IsActive,
    string? ZoneCode = null,
    bool? IsLprEnabled = null,
    bool? IsDynamicPricingEnabled = null,
    decimal? DynamicMinMultiplier = null,
    decimal? DynamicMaxMultiplier = null,
    decimal? PeakHourMultiplier = null,
    decimal? WeekendMultiplier = null,
    bool? HasEvCharging = null,
    int? EvChargerCount = null,
    decimal? EvChargingRatePerHour = null,
    decimal? EvIdleRatePerHour = null,
    int? EvIdleGraceMinutes = null,
    EvPricingMode? EvPricingMode = null,
    decimal? EvRatePerKwh = null,
    ListingCategory? ListingCategory = null,
    bool? InstantBook = null,
    string? TimeZoneId = null,
    bool? IsBayGuidanceEnabled = null,
    bool? IsValetEnabled = null,
    string? DefaultFacilityLevel = null,
    string? DefaultFacilityZone = null,
    string? IndoorGuidanceNotes = null,
    [Range(0, 1000)] int? TwoWheelerPhysicalSpots = null,
    [Range(0, 1000)] int? FourWheelerPhysicalSpots = null
);

public record ParkingSearchDto(
    string? State = null,
    string? City = null,
    string? Address = null,
    double? Latitude = null,
    double? Longitude = null,
    double? RadiusKm = null,
    DateTime? StartDateTime = null,
    DateTime? EndDateTime = null,
    decimal? MinPrice = null,
    decimal? MaxPrice = null,
    PricingType? PricingType = null,
    ParkingType? ParkingType = null,
    VehicleType? VehicleType = null,
    List<string>? Amenities = null,
    double? MinRating = null,
    string? SortBy = null, // price, rating, distance
    bool SortDescending = false,
    int Page = 1,
    int PageSize = 20,
    bool? HasEvCharging = null,
    /// <summary>When true, only residential driveway listings; when false, only commercial.</summary>
    bool? IsResidential = null,
    ListingCategory? ListingCategory = null
);

public record ParkingSearchResultDto(
    List<ParkingSpaceDto> ParkingSpaces,
    int TotalCount,
    int Page,
    int PageSize,
    int TotalPages
);

public record ParkingMapDto(
    Guid Id,
    string Title,
    string Address,
    string City,
    double Latitude,
    double Longitude,
    decimal HourlyRate,
    string? ThumbnailUrl,
    double AverageRating,
    ParkingType ParkingType,
    ListingCategory ListingCategory = ListingCategory.Commercial,
    bool InstantBook = false,
    decimal EffectiveHourlyRate = 0m,
    bool DynamicPricingApplied = false
);


